version: '3'
services:
  redis:
    image: redislabs/redismod
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    env_file:
      - .env

  flask:
    image: orelbaz/coinsite:${TAG}
    container_name: flask
    restart: always
    ports:
      - '5000:5000'
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env
