version: '3'
services:
  redis:
    image: redislabs/redismod
    container_name: redis
    restart: always
    ports:
      - '6379:6379'

  flask:
    image: orelbaz/coin:1.0
    container_name: flask
    restart: always
    ports:
      - '5000:5000'
    volumes:
      - .:/app
    depends_on:
      - redis
