---
- name: Setup Flask Application
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Update system packages
      become: true
      yum:
        name: '*'
        state: latest
      tags: update

    - name: Change directory
      become: true
      command: cd /home/ec2-user/jenkins-test/CoinSite/
      tags: cd

    - name: Install Python dependencies
      become: true
      pip:
        requirements: /home/ec2-user/jenkins-test/CoinSite/requirements.txt
      tags: pip

    - name: Set executable permissions for playbook
      file:
        path: /home/ec2-user/jenkins-test/CoinSite/app.py
        mode: ugo+rx
      become: true

    - name: Copy Flask service file
      become: true
      copy:
        content: |
          [Unit]
          Description=Flask Web Application
          After=network.target

          [Service]
          User=root
          WorkingDirectory=/home/ec2-user/jenkins-test/CoinSite
          ExecStart=/usr/local/bin/flask run --host=0.0.0.0
          Restart=always

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/flask.service
      notify: Restart Flask Service
      tags: service

    - name: Start Flask service
      become: true
      systemd:
        name: flask.service
        state: started
        enabled: yes
      tags: service

  handlers:
    - name: Restart Flask Service
      become: true
      systemd:
        name: flask.service
        state: restarted

    - name: Reload Systemd daemon
      become: true
      shell: systemctl daemon-reload
      changed_when: false
      ignore_errors: true
      tags: service-reload

    - name: Start Flask service (Retry)
      become: true
      systemd:
        name: flask.service
        state: started
        enabled: yes
      tags: service-restart
